name: 'Deploy to mittwald'
description: 'Deploy your code into a mittwald cloud project'
inputs:
  app-id:
    description: 'The app id of your mittwald cloud project'
    required: true
  domain:
    description: 'The domain name that should be configured'
    required: true
  local-dir:
    description: 'Local directory that should be deployed'
    required: false
    default: '.'
  ssh-private-key:
    description: 'SSH private key to use for deployment'
    required: true
  ssh-public-key:
    description: 'SSH public key to use for deployment'
    required: true
  verbosity:
    description: 'Desired output verbosity level'
    required: false
    default: ""
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-id }}
    - ${{ inputs.local-dir }}
    - ${{ inputs.domain }}
    - ${{ inputs.ssh-public-key }}
    - ${{ inputs.ssh-private-key }}